package com.example.springboot.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = true)
@NoArgsConstructor
@AllArgsConstructor
public class Customer extends Person {

    private String custId; // Auto-generated by counting rows
    private String custIcNo; // Format: XXXXXX-XX-XXXX
    private String custPassword; // Plain text password (legacy anti-pattern)

    public Customer(String custIcNo, String custPassword, String name, String email, String phone, String gender) {
        super(name, phone, gender, email);
        this.custIcNo = custIcNo;
        this.custPassword = custPassword;
    }

    // Legacy validation methods - intentionally kept in entity (anti-pattern)

    public boolean getValidPassword(String password) {
        // Basic validation: Check if the password has a minimum length
        if (password.length() > 8) {
            this.custPassword = password;
            return true;
        } else {
            System.out.println("         Password must be more than 8 characters.");
            System.out.printf("\n");
        }
        return false;
    }

    public boolean getValidICNumber(String icNumber) {
        // Basic validation: Check if the I/C number has the expected format
        if (icNumber.matches("\\d{6}-\\d{2}-\\d{4}")) {
            this.custIcNo = icNumber;
            return true;
        } else {
            System.out.println("Invalid I/C number format. Please use the format XXXXXX-XX-XXXX.");
            System.out.printf("\n");
        }
        return false;
    }

    @Override
    public String toString() {
        return String.format("Customer ID: %s\n                I/C Number : %s\n%s",
                custId, custIcNo, super.toString());
    }
}
