package com.example.springboot.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = true)
@NoArgsConstructor
@AllArgsConstructor
public class Passenger extends Person {

    private String passengerId; // Auto-generated by counting rows
    private String passportNo; // Format: [A-Z]\d{8}

    public Passenger(String passportNo, String name, String email, String phoneNumber, String gender) {
        super(name, phoneNumber, gender, email);
        this.passportNo = passportNo;
    }

    // Legacy validation method - intentionally kept in entity (anti-pattern)
    public boolean ValidPassportNo(String passportNo) {
        // Basic validation: Check if the passport contains one letter and 8 digits
        if (passportNo.matches("[A-Z]\\d{8}")) {
            this.passportNo = passportNo;
            return true;
        } else {
            System.out.println("                Invalid Passport Number. Please enter a valid passport number.");
            System.out.printf("\n");
        }
        return false;
    }

    @Override
    public String toString() {
        return String.format("Passenger ID: %s\n                Passport Number : %s\n%s",
                passengerId, passportNo, super.toString());
    }
}
