package com.example.springboot.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = true)
@NoArgsConstructor
@AllArgsConstructor
public class Staff extends Person {

    private String staffId; // Auto-generated by counting rows (e.g., "S001")
    private String position; // e.g., "Manager", "Airline Controller"
    private String stfPass; // Password stored as VARCHAR (legacy anti-pattern)

    public Staff(String position, String stfPass, String name, String phoneNo, String gender,
            String email) {
        super(name, phoneNo, gender, email);
        this.position = position;
        this.stfPass = stfPass;
    }

    // Legacy login method - intentionally kept in entity (anti-pattern)
    public boolean login(String staffID, String staffPassword) {
        if (staffID.equals(this.staffId) && staffPassword.equals(this.stfPass)) {
            return true;
        }
        return false;
    }

    @Override
    public String toString() {
        return "               Staff ID: " + staffId
                + "\n               Staff Position: " + position
                + "\n               Staff name: " + super.getName()
                + "\n               Phone No: " + super.getPhoneNumber()
                + "\n               Gender: " + super.getGender()
                + "\n               Email: " + super.getEmail();
    }
}
